# e1 = Entity.create!(name: 'entity1')
# e2 = Entity.create!(name: 'entity2', parent: e1)
# e3 = Entity.create!(name: 'entity3', parent: e2)

# s1 = Section.create!(name: 'section1', order: 'section1', entity: e1)
# s2 = Section.create!(name: 'section2', order: 'section2', entity: e1)
# s3 = Section.create!(name: 'section3', order: 'section3', entity: e1)
# s4 = Section.create!(name: 'section4', order: 'section4', entity: e2)
# s5 = Section.create!(name: 'section5', order: 'section5', entity: e3)

# fm1 = FieldModel.create!(name: 'field1')
# fm2 = FieldModel.create!(name: 'field2')
# fm3 = FieldModel.create!(name: 'field3')
# fm4 = FieldModel.create!(name: 'field4')
# fm5 = FieldModel.create!(name: 'field5')
# fm6 = FieldModel.create!(name: 'field6')

# am1 = ActionModel.create!(name: 'action1')
# am2 = ActionModel.create!(name: 'action2')
# am3 = ActionModel.create!(name: 'action3')
# am4 = ActionModel.create!(name: 'action4')
# am5 = ActionModel.create!(name: 'action5')
# am6 = ActionModel.create!(name: 'action6')

# en1 = Enum.create!(name: 'enum1')
# en2 = Enum.create!(name: 'enum2')

# em1 = EnumerationMember.create!(name: 'enum_m1', enum: en1)
# em2 = EnumerationMember.create!(name: 'enum_m2', enum: en1)
# em3 = EnumerationMember.create!(name: 'enum_m3', enum: en1)
# em4 = EnumerationMember.create!(name: 'enum_m4', enum: en2)
# em5 = EnumerationMember.create!(name: 'enum_m5', enum: en2)
# em6 = EnumerationMember.create!(name: 'enum_m6', enum: en2)

# dt1 = Datatype.create!(name: 'datatype1')
# dt2 = Datatype.create!(name: 'datatype2')
# dt3 = Datatype.create!(name: 'datatype3')

# FieldOption.create!(field_model: fm1, optionable: en1)
# FieldOption.create!(field_model: fm2, optionable: dt1)
# FieldOption.create!(field_model: fm3, optionable: en2)
# FieldOption.create!(field_model: fm4, optionable: dt2)
# FieldOption.create!(field_model: fm5, optionable: dt3)
# FieldOption.create!(field_model: fm6, optionable: en1)

# a1 = Action.create!(action_model: am1)
# a2 = Action.create!(action_model: am2)
# a3 = Action.create!(action_model: am3)
# a4 = Action.create!(action_model: am4)
# a5 = Action.create!(action_model: am5)
# a6 = Action.create!(action_model: am6)

# f1 = Field.create!(field_model: fm1)
# f2 = Field.create!(field_model: fm2)
# f3 = Field.create!(field_model: fm3)
# f4 = Field.create!(field_model: fm4)
# f5 = Field.create!(field_model: fm5)
# f6 = Field.create!(field_model: fm6)

# SectionElement.create!(section: s1, sectionable: f1)
# SectionElement.create!(section: s1, sectionable: f2)
# SectionElement.create!(section: s1, sectionable: f3)
# SectionElement.create!(section: s1, sectionable: f4)
# SectionElement.create!(section: s2, sectionable: a1)
# SectionElement.create!(section: s2, sectionable: a2)
# SectionElement.create!(section: s3, sectionable: f5)
# SectionElement.create!(section: s3, sectionable: f6)
# SectionElement.create!(section: s4, sectionable: a3)
# SectionElement.create!(section: s5, sectionable: a4)
# SectionElement.create!(section: s5, sectionable: a5)
# SectionElement.create!(section: s5, sectionable: a6)

# TargetLink.create!(entity: e2, action_model: am1)
# TargetLink.create!(entity: e3, action_model: am3)
# TargetLink.create!(entity: e3, action_model: am2)
# TargetLink.create!(entity: e2, action_model: am4)
# TargetLink.create!(entity: e3, action_model: am4)
# TargetLink.create!(entity: e3, action_model: am4)

# Localizable.create!(type_of: 'description', language: 'Fr', value: 'description Fr 1', localizable: e1)
# Localizable.create!(type_of: 'description', language: 'Fr', value: 'description Fr 2', localizable: am1)
# Localizable.create!(type_of: 'description', language: 'Fr', value: 'description Fr 3', localizable: a1)
# Localizable.create!(type_of: 'description', language: 'Fr', value: 'description Fr 4', localizable: f1)
# Localizable.create!(type_of: 'description', language: 'Fr', value: 'description Fr 5', localizable: fm1)
# Localizable.create!(type_of: 'description', language: 'Fr', value: 'description Fr 6', localizable: en1)
# Localizable.create!(type_of: 'description', language: 'Fr', value: 'description Fr 7', localizable: dt1)
# Localizable.create!(type_of: 'description', language: 'Fr', value: 'description Fr 8', localizable: em1)

# Localizable.create!(type_of: 'label', language: 'Fr', value: 'label Fr 1', localizable: e1)
# Localizable.create!(type_of: 'label', language: 'Fr', value: 'label Fr 2', localizable: am1)
# Localizable.create!(type_of: 'label', language: 'Fr', value: 'label Fr 3', localizable: a1)
# Localizable.create!(type_of: 'label', language: 'Fr', value: 'label Fr 4', localizable: f1)
# Localizable.create!(type_of: 'label', language: 'Fr', value: 'label Fr 5', localizable: fm1)
# Localizable.create!(type_of: 'label', language: 'Fr', value: 'label Fr 6', localizable: en1)
# Localizable.create!(type_of: 'label', language: 'Fr', value: 'label Fr 7', localizable: dt1)
# Localizable.create!(type_of: 'label', language: 'Fr', value: 'label Fr 8', localizable: em1)

# Localizable.create!(type_of: 'description', language: 'En', value: 'description En 1', localizable: e1)
# Localizable.create!(type_of: 'description', language: 'En', value: 'description En 2', localizable: am1)
# Localizable.create!(type_of: 'description', language: 'En', value: 'description En 3', localizable: a1)
# Localizable.create!(type_of: 'description', language: 'En', value: 'description En 4', localizable: f1)
# Localizable.create!(type_of: 'description', language: 'En', value: 'description En 5', localizable: fm1)
# Localizable.create!(type_of: 'description', language: 'En', value: 'description En 6', localizable: en1)
# Localizable.create!(type_of: 'description', language: 'En', value: 'description En 7', localizable: dt1)
# Localizable.create!(type_of: 'description', language: 'En', value: 'description En 8', localizable: em1)

# Localizable.create!(type_of: 'label', language: 'En', value: 'label En 1', localizable: e1)
# Localizable.create!(type_of: 'label', language: 'En', value: 'label En 2', localizable: am1)
# Localizable.create!(type_of: 'label', language: 'En', value: 'label En 3', localizable: a1)
# Localizable.create!(type_of: 'label', language: 'En', value: 'label En 4', localizable: f1)
# Localizable.create!(type_of: 'label', language: 'En', value: 'label En 5', localizable: fm1)
# Localizable.create!(type_of: 'label', language: 'En', value: 'label En 6', localizable: en1)
# Localizable.create!(type_of: 'label', language: 'En', value: 'label En 7', localizable: dt1)
# Localizable.create!(type_of: 'label', language: 'En', value: 'label En 8', localizable: em1)
